- name: GETTING CONFIGURATION BACKUP
  hosts: F5_PROD
  gather_facts: false
  connection: local

  vars:
    backup_dir: "/home/dxc-network/Bureau"

  tasks:
    - name: Backup F5 prod
      block:
        - name: Fetch the UCS backup
          bigip_ucs_fetch:
            src: cs_backup.ucs
            dest: "{{ backup_dir }}/equipments/F5_prod/F5_PROD_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.conf"
            provider:
              server: "{{ ansible_host }}}"
              user: "{{ f5_user }}"
              password: "{{ f5_pass }}"
            delegate_to: localhost
        
        - name: Write SUCCESS result
          ansible.builtin.copy:
            content: "{{ {
              'job': 'FortiGate DC Backup',
              'status': 'SUCCESS',
              'host': inventory_hostname,
              'ip': ansible_host,
              'timestamp': now().strftime('%Y-%m-%d %H:%M:%S')} | to_nice_json }}"
            dest: "{{ backup_dir }}/backup_results/fgcfc.json"
            mode: "0640"
      rescue:
        - name: Write FAILED result
          ansible.builtin.copy:
            content: "{{ {
              'job': 'FortiGate DC Backup',
              'status': 'FAILED',
              'host': inventory_hostname,
              'ip': ansible_host,
              'timestamp': now().strftime('%Y-%m-%d %H:%M:%S')} | to_nice_json }}"
            dest: "{{ backup_dir }}/backup_results/fgcfc.json"
            mode: "0640"
        - name: Fail the job
          ansible.builtin.fail:
            msg: "FortiGate configuration backup failed"
