- name: GETTING CONFIGURATION BACKUP
  hosts: FORTIGATE_DC
  gather_facts: false
  vars:
    ansible_connection: ansible.netcommon.httpapi
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_command_timeout: 120
  tasks:
    - name: Export running configuration
      fortinet.fortios.fortios_export_config_playbook:
        selectors:
          - selector: system_status
        output_path: "/home/dxc-network/Bureau"
      register: fgt_export
