- name: GETTING CONFIGURATION BACKUP
  hosts: FORTIGATE_CFC
  gather_facts: false
  connection: local

  vars:
    backup_dir: "/home/dxc-network/Bureau/equipments/FortigateCFC"

  tasks:
    - name: Backup FortiGate
      block:
        - name: Get FortiGate configuration backup
          ansible.builtin.uri:
            url: "https://{{ ansible_host }}:{{ forti_port }}/api/v2/monitor/system/config/backup?scope=global"
            method: POST
            headers:
              Authorization: "Bearer {{ api_key }}"
            validate_certs: false
            return_content: true
          register: fgt_config
          changed_when: false
          no_log: true
        
        - name: Save configuration backup
          ansible.builtin.copy:
            content: "{{ fgt_config.content }}"
            dest: "{{ backup_dir }}/FortiGate_CFC_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.conf"
            mode: "0640"
        - name: Write SUCCESS result
          ansible.builtin.copy:
            content: "{{ {
              'job': 'FortiGate DC Backup',
              'status': 'SUCCESS',
              'host': inventory_hostname,
              'ip': ansible_host,
              'timestamp': now().strftime('%Y-%m-%d %H:%M:%S')} | to_nice_json }}"
            dest: "{{ backup_dir }}/backup_results/fgcfc.json"
            mode: "0640"
      rescue:
        - name: Write FAILED result
          ansible.builtin.copy:
            content: "{{ {
              'job': 'FortiGate DC Backup',
              'status': 'FAILED',
              'host': inventory_hostname,
              'ip': ansible_host,
              'timestamp': now().strftime('%Y-%m-%d %H:%M:%S')} | to_nice_json }}"
            dest: "{{ backup_dir }}/backup_results/fgcfc.json"
            mode: "0640"
        - name: Fail the job
          ansible.builtin.fail:
            msg: "FortiGate configuration backup failed"
