- name: GETTING CONFIGURATION BACKUP
- hosts: FORTIGATE_DC
  gather_facts: false
  vars:
    ansible_connection: ansible.netcommon.httpapi
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
  tasks:
    - name: Export running config as playbook/backup
      fortinet.fortios.fortios_export_config_playbook:
      register: fgt_backup

    - name: Save configuration backup to local file
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ fgt_config.stdout }}"
        dest: "/home/dxc-network/Bureau/{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y_%m_%d___%H_%M_%S') }}.cfg"
